# Generated by Django 4.0.7 on 2022-09-17 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('interests', models.CharField(choices=[('movie', 'Movies, Actors, Directors, Genres, ...'), ('science', 'Physics, Biology, Chemistry, Zoology, Astronomy, Medicine, Astrophysics, Earth Sciences, ...'), ('culture', 'Arts, Society, Philosophy, ...'), ('sports', 'Football, Basketball, Soccer, Tennis, ...'), ('food', 'Vegetables, Fruits, Grains, Beans, Nuts, Meat, Poultry, Seafood, Dairy, ...'), ('fashion', 'Vintage, Artsy, Casual, Grunge style clothing, Chic, Bohemian, Sexy, Exotic, ...'), ('pets', 'Cats, Dogs, Birds, Rabbits, Horses, Ferrets, Fish, ...'), ('joke', 'Observational, Anecdotal, Situational, Character, One-liner, Ironic, Deadpan, Farcical, Self-deprecating, Slapstick, ...'), ('politics', 'Band society, Chiefdom, Empires, Leagues, ...'), ('adventure', 'Yoga, Trekking, Cycling, Canoeing, Kayaking, Rock climbing, Multi-adventure travel, New Zealand, ...')], max_length=64)),
                ('journey_frequency', models.IntegerField()),
                ('cluster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserProfileCluster', to='schindler.cluster')),
            ],
        ),
    ]
